### PR TITLE
PCD Viewer

### PR DESCRIPTION
**Pull request by ommmid**
Added a node to load any *.pcd file and display it with "pcl::visualization::CloudViewer".

### CODE REVIEW

**Comment by jontromanab** [comment]
- The pcd_viewer code can be easily executed by pcl_viewer from point cloud library. However I am going to keep it.
- The sq_test_node is unnecessary
**sampling_test_pcd.cpp**
- There is a nice documentation of shared, unique and raw pointer. why it is there? (Possibly remove it)
- The comments in line 28, 52 and 62 does not make much sense. (Possibly remove them)

**Comment by ommmid** [comment]
Comments are only for my understanding. And sq_test_node was just a test. All will be removed

**Comment by jontromanab** [comment]
Ok. remove them. Otherwise they will be merged.

**Comment by jontromanab** [comment]
ok. I am merging this. It is OK, as it is a small kind-of-testing development. But from the next time, try to create a branch naming the module you are developing and create a PR from there. Best practice and we can keep track of changes.

**Pull request merged**
